#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { 
  unshift @INC, "$FindBin::Bin/../lib";
  if (-d "$FindBin::Bin/../../Mojolicious-Plugin-FeedReader/lib") {
    unshift @INC, "$FindBin::Bin/../../Mojolicious-Plugin-FeedReader/lib";
  }
  binmode STDERR, ':utf8';
  binmode STDOUT, ':utf8';
 }

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Hadashot');
